name: Node.js CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name : Change working directory to frontend
        run: |
            cd /my-app
            npm install
      - name : Run test
        run: |
            cd /my-app/src
            npm test
            
