name: Node.js CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name : Change working directory to frontend
        run: npm install
        working-directory: my-app
      - name : Run test
        run: npm test
        working-directory: src
        
            
